title: karanversation
description: Engineering, Programming, (wannabe) Physics and Robotics
baseurl: ""
url: "https://karanversation.github.io"

theme: minima

markdown: kramdown

plugins:
  - jekyll-feed

